### ISSUE TITLE
Rewrite it in Rust.

### ISSUE THREAD

**Issue by EliasAuret** [Arcade-Classics/Arcade-Classics#10]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when something isn't written in Rust.

**Describe the solution you'd like**
Rewrite it in Rust.

**Describe alternatives you've considered**
There is no alternative to rewriting it in Rust.

**Additional context**
Rust.

**Comment by Hugo-Maxted** [comment]
We have had internal discussions about doing this for a while but have been unable to proceed due to certain team members love for javascript and inability to try new things.

**Comment by EliasAuret** [comment]
skill issue
