### ISSUE TITLE
minesweeper sucks

### ISSUE THREAD

**Issue by EddieTheEd** [Arcade-Classics/Arcade-Classics#7]

**Comment by EddieTheEd** [comment]
step 1: play a game of minesweeper above easy difficulty
step 2: in the middle close the extension
step 3: reopen extension

result: upon pressing the resume game button, the minesweeper starts as if it was in easy difficulty. 

please fix this ruined my experience i will be leaving a 2/5 stars on yelp

**Comment by Hugo-Maxted** [comment]
Duplicate of #1
