### ISSUE TITLE
Leaderboard Bad

### ISSUE THREAD

**Issue by Grim4Reaper** [Arcade-Classics/Arcade-Classics#8]
I have been removed from the leaderboards. This is annoying because I was in the top 10 for 5 leaderboards.

PLEASE FIX.

I will be leaving sqrt(-1)/5 stars on yelp.

**Comment by Hugo-Maxted** [comment]
Hi Grim4Reaper, we have reviewed the internal database and you have been overtaken on these leader-boards, you may not have noticed this immediately as leader-board can take time to update.
